# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoTwitter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoTwitter
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'SwiftyUserDefaults', '~> 4.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'KWDrawerController'
  pod 'lottie-ios'

  target 'DemoTwitterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
